### PR TITLE
fix(docs): updates docs due to ui folder migration and adds steps for local dev-env

### PR DESCRIPTION
**Pull request by olandr**
The PR #567 removed the ui directory and migrated the Greenhouse UI to https://github.com/cloudoperators/juno. 

This PR updates various broken references, links and configurations to accommodate for this migration. It also adds steps for building the [juno-app-greenhouse](https://github.com/cloudoperators/juno/pkgs/container/juno-app-greenhouse) locally.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Related PR #567

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

## Added to documentation?

- [ ] 📜 README.md
- [x] 🤝 Documentation pages updated
- [ ] 🙅 no documentation needed
- [ ] (if applicable) generated OpenAPI docs for CRD changes

Documentation will be handled in a separate PR.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by olandr** [comment]
This would possibly render the branch [ui-before-migration](https://github.com/cloudoperators/greenhouse/tree/ui-before-migration) redundant.

**Comment by olandr** [comment]
@abhijith-darshan How does this PR play with yours #775? This PR is changing docs and making the local dev a bit easier to do, but your PR is a completely changing it.

You do not touch the juno/ui thing right? So maybe we pivot this PR to be focusing on how to play ball with that change?

**Comment by abhijith-darshan** [comment]
> @abhijith-darshan How does this PR play with yours #775? This PR is changing docs and making the local dev a bit easier to do, but your PR is a completely changing it.
> 
> You do not touch the juno/ui thing right? So maybe we pivot this PR to be focusing on how to play ball with that change?

@olandr - both solutions exist side by side for now until the new KinD based setup reaches parity with the docker-compose setup. So I would say go ahead and continue with your PR.

**Review by IvoGoman — APPROVED** [review]
Thanks for the improvements @olandr 🥇

**Pull request merged**
