### PR TITLE
Feat(manifests): Generate Typescript types from CRDs

### PR DESCRIPTION
**Pull request by uwe-mayer**
This adds a `make` target to generate the Typescript types ingested by the uis when recreating the `manifests` of the greenhouse crontroller.

### CODE REVIEW

**Review by IvoGoman — APPROVED** [review]

**Comment by IvoGoman** [comment]
Noticed that there are changes to `schema.d.ts` when I run `make generate-types`. Should we add these changes to the PR?

**Comment by uwe-mayer** [comment]
> Noticed that there are changes to `schema.d.ts` when I run `make generate-types`. Should we add these changes to the PR?

It's just reorder of the CRDs, right? Yes can always be committed, but make no difference imho.

**Review by ArtieReus — CHANGES_REQUESTED** [review]
I would increase the version please :)

**Comment by uwe-mayer** [comment]
> I would increase the version please :)

Version is updated :)

**Review by ArtieReus — APPROVED** [review]
lgtm

**Pull request merged**
